services:
  pipeline-service:
    build: .
    image: dotnet-8-python-310
    env_file:
      - .env
    volumes:
      - .:/app
    shm_size: '6gb'
    networks:
      - stock-backend
  initialize-jupyter-lab:
    build: .
    image: dotnet-8-python-310
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - .:/app
    tty: true
    command: jupyter lab --ip=0.0.0.0 --no-browser --LabApp.token=''
  initialize-fastapi:
    build: .
    image: dotnet-8-python-310
    env_file:
      - .env
    ports:
      - "127.0.0.1:${API_PORT:-8002}:8000"
    volumes:
      - .:/app
    tty: true
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      stock-backend:
        aliases:
          - ml-api
  initialize-analytics-hub:
    build: .
    image: dotnet-8-python-310
    ports:
      - "127.0.0.1:8501:8501"
    volumes:
      - .:/app
    tty: true
    command: streamlit run analytics_hub.py --server.address=0.0.0.0 --server.port=8501

networks:
  stock-backend:
    external: true
    name: stock-analysis-backend
